import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {MapLibreOverlay} from '@deck.gl/maplibre';
import {H3HexagonLayer} from '@deck.gl/geo-layers';
import {GeoJsonLayer,ScatterplotLayer} from '@deck.gl/layers';
import {Map,useMap,useControl,NavigationControl,GeolocateControl,FullscreenControl,ScaleControl} from 'react-map-gl/maplibre';
import type {MapRef} from 'react-map-gl/maplibre';
import MapboxDraw from 'maplibre-gl-draw';
import type {FeatureCollection} from 'geojson';
import * as h3 from 'h3-js';
import 'maplibre-gl/dist/maplibre-gl.css';
import 'maplibre-gl-draw/dist/mapbox-gl-draw.css';
const API='http://localhost:8000';
const BASEMAPS:any={liberty:{name:'Liberty',url:'https://tiles.openfreemap.org/styles/liberty'},bright:{name:'Bright',url:'https://tiles.openfreemap.org/styles/bright'},positron:{name:'Positron',url:'https://tiles.openfreemap.org/styles/positron'},dark:{name:'Dark',url:'https://tiles.openfreemap.org/styles/dark'},fiord:{name:'Fiord',url:'https://tiles.openfreemap.org/styles/fiord'},colorful:{name:'Colorful',url:'https://tiles.versatiles.org/assets/styles/colorful/style.json'}};
const DATA_COLOR_STYLES:any={default:{name:'Default Blue',entity:'#2563eb',fill:'#2563eb',line:'#1d4ed8',opacity:.13},emerald:{name:'Emerald',entity:'#059669',fill:'#10b981',line:'#047857',opacity:.15},amber:{name:'Amber',entity:'#d97706',fill:'#f59e0b',line:'#b45309',opacity:.16},violet:{name:'Violet',entity:'#7c3aed',fill:'#8b5cf6',line:'#6d28d9',opacity:.15},mono:{name:'Monochrome',entity:'#374151',fill:'#6b7280',line:'#1f2937',opacity:.14}};
type Dataset={dataset_id:number;dataset:string;data_type:string;h3_resolution:number;feature_count:number;part_count:number;boundary_h3_count:number;metadata?:Record<string,any>;created_at?:string;updated_at?:string;source?:string;owner?:string;version?:string;source_format?:string;geographic_coverage?:Record<string,any>;tags?:string[];license?:string;update_frequency?:string;schema?:Record<string,any>;lineage?:Record<string,any>};
type Entity={entity_id:any;latitude:number;longitude:number;[key:string]:any};
function rgb(hex:string){const n=parseInt(hex.replace('#',''),16);return[(n>>16)&255,(n>>8)&255,n&255]}
function uniq<T>(a:T[]){return[...new Set(a)]}
function bounds(fs:any[]){let a=[Infinity,Infinity],b=[-Infinity,-Infinity];const w=(x:any)=>Array.isArray(x)&&typeof x[0]==='number'?(a=[Math.min(a[0],x[0]),Math.min(a[1],x[1])],b=[Math.max(b[0],x[0]),Math.max(b[1],x[1])]):Array.isArray(x)&&x.forEach(w);fs.forEach(f=>w(f.geometry?.coordinates));return a[0]===Infinity?null:[a,b]}
function DeckGLOverlay({layers}:{layers:any[]}){const overlay=useControl<MapLibreOverlay>(()=>new MapLibreOverlay({interleaved:true,layers}));overlay.setProps({layers,interleaved:true});return null}
function DrawBridge({ready,onChange}:{ready:(d:MapboxDraw|null)=>void;onChange:(fc:FeatureCollection)=>void}){const {current}=useMap();useEffect(()=>{const map=current as any;if(!map)return;let draw:MapboxDraw|null=null;let disposed=false;const sync=()=>{if(draw&&!disposed)onChange(draw.getAll() as FeatureCollection)};const attach=()=>{if(disposed||draw)return;draw=new MapboxDraw({displayControlsDefault:false,controls:{point:false,line_string:false,polygon:false,trash:false}});map.addControl(draw as any,'top-right');ready(draw);sync();for(const event of ['draw.create','draw.update','draw.delete','draw.combine','draw.uncombine'])map.on(event,sync)};if(typeof map.loaded==='function'&&map.loaded())attach();else map.once('load',attach);return()=>{disposed=true;for(const event of ['draw.create','draw.update','draw.delete','draw.combine','draw.uncombine']){try{map.off(event,sync)}catch{}}if(draw){try{map.removeControl(draw as any)}catch{}}ready(null);draw=null}},[current,ready,onChange]);return null}
export default function App(){
 const mapRef=useRef<MapRef>(null),drawRef=useRef<MapboxDraw|null>(null);
 const [page,setPage]=useState('map'),[datasets,setDatasets]=useState<Dataset[]>([]),[dataset,setDataset]=useState<Dataset|null>(null);
 const [entities,setEntities]=useState<Entity[]>([]),[cells,setCells]=useState<string[]>([]),[resolution,setResolution]=useState(11);
 const [h3Visible,setH3Visible]=useState(true),[entityVisible,setEntityVisible]=useState(true),[resultOpen,setResultOpen]=useState(false),[results,setResults]=useState<any[]>([]);
 const [height3d,setHeight3d]=useState(Number(localStorage.getItem('h3-height-3d')||120)),[extruded3d,setExtruded3d]=useState(localStorage.getItem('h3-extruded-3d')==='true');
 const [analyticsMode,setAnalyticsMode]=useState(localStorage.getItem('h3-analytics-mode')||'off'),[analyticsRows,setAnalyticsRows]=useState<any[]>([]);
 const [dark,setDark]=useState(localStorage.getItem('h3-theme')==='dark'),[basemap,setBasemap]=useState(localStorage.getItem('h3-basemap')||'liberty');
 const [stats,setStats]=useState(false),[toast,setToast]=useState('');
 const [colors,setColors]=useState(()=>({entity:localStorage.getItem('h3-entity-color')||'#2563eb',fill:localStorage.getItem('h3-h3-color')||'#2563eb',line:localStorage.getItem('h3-h3-line-color')||'#1d4ed8',opacity:Number(localStorage.getItem('h3-h3-opacity')||13)/100}));
 const [dataStyle,setDataStyle]=useState(localStorage.getItem('h3-data-style')||'default');
 const applyDataStyle=(key:string)=>{const s=DATA_COLOR_STYLES[key];if(!s)return;setDataStyle(key);setColors({entity:s.entity,fill:s.fill,line:s.line,opacity:s.opacity});localStorage.setItem('h3-data-style',key);localStorage.setItem('h3-entity-color',s.entity);localStorage.setItem('h3-h3-color',s.fill);localStorage.setItem('h3-h3-line-color',s.line);localStorage.setItem('h3-h3-opacity',String(Math.round(s.opacity*100)))};
 const updateDataColor=(key:string,value:any)=>{setDataStyle('custom');localStorage.setItem('h3-data-style','custom');setColors((c:any)=>{const next={...c,[key]:value};localStorage.setItem(key==='entity'?'h3-entity-color':key==='fill'?'h3-h3-color':key==='line'?'h3-h3-line-color':'h3-h3-opacity',key==='opacity'?String(Math.round(value*100)):value);return next})};
 const [ingMode,setIngMode]=useState<'file'|'draw'>('file'),[ingName,setIngName]=useState(''),[ingRes,setIngRes]=useState(11),[ingData,setIngData]=useState<FeatureCollection|null>(null),[preview,setPreview]=useState<any>(null);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(''),2200)};
 const refresh=useCallback(async()=>{try{const d=await fetch(API+'/ingestion/datasets').then(r=>r.json());setDatasets(d.datasets||[])}catch{notify('API unavailable')}},[]);
 useEffect(()=>{refresh()},[refresh]);
 const load=useCallback(async(name:string)=>{const m=datasets.find(x=>x.dataset===name);if(!m)return;setDataset(m);setResolution(m.h3_resolution);
  try{const r=await fetch(API+'/ingestion/dataset/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset:name,limit:0,resolution:m.h3_resolution})});const d=await r.json();if(!r.ok)throw Error(d.detail||'preview failed');
   const es=(d.features||[]).map((f:any)=>({entity_id:f.properties?.entity_id,latitude:f.geometry?.coordinates?.[1],longitude:f.geometry?.coordinates?.[0],...f.properties})).filter((x:any)=>Number.isFinite(x.latitude));
   setEntities(es);setCells(uniq((d.features||[]).map((f:any)=>f.properties?.h3_index).filter(Boolean)));
   try{const ar=await fetch(API+'/analytics/h3?dataset='+encodeURIComponent(name)+'&resolution='+m.h3_resolution+'&limit=50000').then(x=>x.json());setAnalyticsRows(ar.rows||[])}catch{setAnalyticsRows([])}
   const b=bounds(d.features||[]);if(b)mapRef.current?.fitBounds(b as any,{padding:{top:90,bottom:90,left:360,right:60},maxZoom:15,duration:700});notify('แสดงข้อมูลทั้งหมดของ '+name)
  }catch(e){notify(e instanceof Error?e.message:'Load failed')}
 },[datasets]);
 const display=useMemo(()=>{const out=uniq(cells.flatMap(c=>{try{const r=h3.getResolution(c);return resolution===r?[c]:resolution<r?[h3.cellToParent(c,resolution)]:resolution-r>4?[]:h3.cellToChildren(c,resolution)}catch{return[]}}));return out.slice(0,250000)},[cells,resolution]);
 const analyticsMap=useMemo(()=>new globalThis.Map<string,any>(analyticsRows.map(x=>[x.h3_index,x])),[analyticsRows]);
 const analyticsMax=useMemo(()=>{if(analyticsMode==='entity_count')return Math.max(0,...analyticsRows.map(x=>Number(x.entity_count)||0));if(analyticsMode==='coverage')return Math.max(0,...analyticsRows.map(x=>Number(x.polygon_coverage??x.avg_cell_coverage)||0));return 0},[analyticsRows,analyticsMode]);
 const layers=useMemo(()=>[
  new H3HexagonLayer({id:'h3-gpu',data:display.map(hex=>({hex})),pickable:true,highPrecision:'auto',filled:true,wireframe:extruded3d,extruded:extruded3d,elevationScale:1,
   getHexagon:(d:any)=>d.hex,getElevation:()=>height3d,getFillColor:(d:any)=>{const a=analyticsMap.get(d.hex);const value=analyticsMode==='entity_count'?Number(a?.entity_count)||0:Number(a?.polygon_coverage??a?.avg_cell_coverage)||0;const factor=analyticsMode==='off'||analyticsMax<=0?1:.35+.65*Math.min(1,value/analyticsMax);const c=rgb(colors.fill);return[Math.round(c[0]*factor),Math.round(c[1]*factor),Math.round(c[2]*factor),Math.round(colors.opacity*255)] as any},getLineColor:()=>[...rgb(colors.line),255] as any,lineWidthMinPixels:1,visible:h3Visible,
   onClick:(i:any)=>i.object&&(setResults([i.object]),setResultOpen(true))}),
  new ScatterplotLayer({id:'entity-gpu',data:entities,pickable:true,getPosition:(d:any)=>[d.longitude,d.latitude],getRadius:45,radiusMinPixels:4,radiusMaxPixels:9,getFillColor:()=>[...rgb(colors.entity),230] as any,visible:entityVisible,
   onClick:(i:any)=>i.object&&(setResults([i.object]),setResultOpen(true))}),
  new GeoJsonLayer({id:'query-result',data:results.length?{type:'FeatureCollection',features:results.filter(x=>x.geometry)}:undefined,filled:true,stroked:true,getFillColor:[37,99,235,45],getLineColor:[37,99,235,220],getLineWidth:2})
 ],[display,entities,colors,h3Visible,entityVisible,results,extruded3d,height3d,analyticsMap,analyticsMode,analyticsMax]);
 const runQuery=async()=>{if(!dataset)return notify('เลือก Dataset ก่อน');const field=(document.getElementById('qField') as HTMLSelectElement).value,op=(document.getElementById('qOp') as HTMLSelectElement).value,value=(document.getElementById('qValue') as HTMLInputElement).value;
  const spatialType=(document.getElementById('qSpatial') as HTMLSelectElement).value,spatial:any={type:spatialType};if(spatialType==='nearby'){const c=mapRef.current?.getCenter();spatial.lat=c?.lat;spatial.lng=c?.lng;spatial.radius_m=Number((document.getElementById('qDistance') as HTMLInputElement).value||1000)}
  if(spatialType==='bbox'){const b=mapRef.current?.getBounds();spatial.min_lat=b?.getSouth();spatial.max_lat=b?.getNorth();spatial.min_lng=b?.getWest();spatial.max_lng=b?.getEast()}
  try{const r=await fetch(API+'/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset:dataset.dataset,conditions:value?[{field,operator:op,value:field==='attribute'?JSON.parse(value):value}]:[],spatial,limit:5000})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Query failed');setResults(d.features||[]);setResultOpen(true);notify('Query สำเร็จ '+(d.features||[]).length.toLocaleString())}catch(e){notify(e instanceof Error?e.message:'Query failed')}};
 const execute=async()=>{if(!ingData||!ingName)return notify('ใส่ Dataset Name และ source ก่อน');const r=await fetch(API+'/ingestion/geojson/execute?resolution='+ingRes+'&dataset='+encodeURIComponent(ingName),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ingData)});const d=await r.json();if(!r.ok)return notify(d.detail||'Execute failed');notify('Ingestion completed: '+d.dataset);await refresh();setPage('map')};
 const file=async(f:File)=>{try{setIngData(JSON.parse(await f.text()));notify('โหลด GeoJSON แล้ว')}catch{notify('GeoJSON ไม่ถูกต้อง')}};
 const ready=useCallback((d:MapboxDraw|null)=>{drawRef.current=d},[]);
 const onDrawChange=useCallback((fc:FeatureCollection)=>{setIngData(fc);setPreview(null)},[]);
 const useDraw=()=>{const d=drawRef.current?.getAll();if(d?.features.length){setIngData(d);notify('รับข้อมูลจากแผนที่ '+d.features.length+' feature(s)')}else notify('ยังไม่มีข้อมูลที่วาด')};
 const style=dark?BASEMAPS.dark.url:BASEMAPS[basemap].url;
 const dataStyleOptions=Object.entries(DATA_COLOR_STYLES);
 return <div className={dark?'app dark':'app'}><aside className="sidebar"><div className="brand"><b>H3 DATA PLATFORM</b><small>GPU SPATIAL DATA PLATFORM</small></div>
 <Nav id="dashboard" p={page} set={setPage} t="▦ Dashboard"/><Nav id="datasets" p={page} set={setPage} t="▤ Datasets"/><Nav id="ingestion" p={page} set={setPage} t="↥ Ingestion"/><Nav id="map" p={page} set={setPage} t="⌖ Map"/><Nav id="analysis" p={page} set={setPage} t="⌁ Analysis"/><Nav id="settings" p={page} set={setPage} t="⚙ Settings"/>
 <div className="sideFoot">React + TypeScript<br/>MapLibre + deck.gl H3</div></aside>
 <main className="workspace"><header className="topbar"><b>{page}</b><input placeholder="Search dataset, entity, H3 index..."/><button onClick={()=>setStats(!stats)}>▥</button><button onClick={()=>setDark(!dark)}>{dark?'☾':'☀'}</button></header>
 {page==='map'&&<section className="mapPage"><Map ref={mapRef} mapStyle={style} dragRotate={true} touchZoomRotate={true} touchPitch={true}><NavigationControl position="top-right" showZoom showCompass visualizePitch/><GeolocateControl position="top-right" positionOptions={{enableHighAccuracy:true,timeout:6000}} trackUserLocation={false} showUserLocation showAccuracyCircle/><FullscreenControl position="top-right"/><ScaleControl position="bottom-left" unit="metric" maxWidth={110}/><DeckGLOverlay layers={layers}/></Map>
 <MapPanel {...{datasets,dataset,load,resolution,setResolution,h3Visible,setH3Visible,entityVisible,setEntityVisible,colors,setColors,dataStyle,applyDataStyle,updateDataColor,dataStyleOptions,basemap,setBasemap,height3d,setHeight3d,extruded3d,setExtruded3d,analyticsMode,setAnalyticsMode,analyticsRows,runQuery}}/>
 {stats&&<div className="stats"><b>Dataset<br/>{dataset?.dataset||'—'}</b><b>Entities<br/>{dataset?.feature_count?.toLocaleString()||'—'}</b><b>H3<br/>GPU</b><b>Visible<br/>{display.length.toLocaleString()}</b></div>}
 {resultOpen&&<Results data={results} close={()=>setResultOpen(false)}/>}</section>}
 {page==='ingestion'&&<section className="page"><h2>Ingestion Pipeline</h2><p>GeoJSON หรือ Draw → Boundary H3</p><div className="grid2"><div className="card"><div className="buttonRow"><button className={ingMode==='file'?'primary':''} onClick={()=>setIngMode('file')}>📄 File / GeoJSON</button><button className={ingMode==='draw'?'primary':''} onClick={()=>setIngMode('draw')}>✏️ Draw</button></div><label>Dataset Name<input value={ingName} onChange={e=>setIngName(e.target.value)}/></label><label>H3 Resolution<select value={ingRes} onChange={e=>setIngRes(+e.target.value)}>{Array.from({length:11},(_,i)=><option key={i} value={i+5}>Res {i+5}</option>)}</select></label>
 {ingMode==='file'?<label className="drop">Drop GeoJSON<input type="file" accept=".geojson,.json" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label>:<><div className="drawMap"><Map mapStyle={style} initialViewState={{longitude:100.5018,latitude:13.7563,zoom:11}} dragRotate touchZoomRotate><DrawBridge ready={ready} onChange={onDrawChange}/></Map></div><div className="buttonRow"><button className="primary" onClick={()=>drawRef.current?.changeMode('draw_point')}>Point</button><button className="primary" onClick={()=>drawRef.current?.changeMode('draw_line_string')}>Line</button><button className="primary" onClick={()=>drawRef.current?.changeMode('draw_polygon')}>Polygon</button><button onClick={()=>drawRef.current?.changeMode('simple_select')}>Select / Move</button><button onClick={()=>{const id=drawRef.current?.getSelectedIds?.()[0];if(id)drawRef.current?.changeMode('direct_select',{featureId:id});else notify('เลือก Feature ก่อน Edit vertices')}}>Edit Vertices</button><button onClick={useDraw}>Use Drawing</button><button onClick={()=>{drawRef.current?.deleteAll();setIngData({type:'FeatureCollection',features:[]});setPreview(null)}}>Clear</button></div><div className="drawStatus">{ingData?.features.length||0} feature(s) · วาดเสร็จแล้วข้อมูลจะเข้า Pipeline อัตโนมัติ</div></>}
 <div className="buttonRow"><button onClick={async()=>{if(!ingData)return notify('เลือก source ก่อน');const r=await fetch(API+'/ingestion/geojson/preview?resolution='+ingRes,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ingData)});const d=await r.json();setPreview(d);notify(r.ok?'Preview ready':d.detail||'Preview failed')}}>Preview H3</button><button className="primary" onClick={execute}>Execute Pipeline</button></div></div><div className="card"><b>Preview</b><pre className="preview">{preview?JSON.stringify(preview,null,2):'Waiting for source'}</pre></div></div></section>}
 {page==='datasets'&&<DatasetsPage datasets={datasets} refresh={refresh} onViewMap={(name)=>{setPage('map');load(name)}} onNew={()=>setPage('ingestion')} onNotify={notify}/>}
 {page==='dashboard'&&<section className="page"><h2>Dashboard</h2><div className="kpis"><b>{datasets.length}<small>Datasets</small></b><b>{entities.length.toLocaleString()}<small>Entities</small></b><b>{cells.length.toLocaleString()}<small>H3 Cells</small></b><b>WebGL<small>Renderer</small></b></div></section>}
 {page==='analysis'&&<section className="page"><h2>Analysis</h2><div className="card">Dataset: {dataset?.dataset||'—'}<br/>Results: {results.length.toLocaleString()}</div></section>}
 {page==='settings'&&<section className="page"><h2>Settings</h2><div className="card"><b>Renderer</b><p>React + TypeScript + Vite + MapLibre + deck.gl H3HexagonLayer</p><p>H3 indexes are rendered directly by the GPU. No cellToBoundary → GeoJSON conversion for display.</p></div></section>}
 {toast&&<div className="toast">{toast}</div>}</main></div>
}
function Nav({id,p,set,t}:{id:string;p:string;set:(x:string)=>void;t:string}){return <button className={'nav '+(p===id?'active':'')} onClick={()=>set(id)}>{t}</button>}
function MapPanel(p:any){return <aside className="panel left"><div className="section"><b>Dataset</b><select value={p.dataset?.dataset||''} onChange={e=>p.load(e.target.value)}><option value="">Select dataset</option>{p.datasets.map((d:any)=><option key={d.dataset}>{d.dataset}</option>)}</select><div className="card"><b>{p.dataset?.dataset||'No dataset'}</b><small>Res {p.dataset?.h3_resolution||'—'} · {p.dataset?.feature_count?.toLocaleString()||0} entities</small></div></div>
 <div className="section"><b>Layers</b><Check t="Entities" v={p.entityVisible} s={p.setEntityVisible}/><Check t="H3 GPU" v={p.h3Visible} s={p.setH3Visible}/></div>
 <div className="section"><b>Data Colors</b><label>Style<select value={p.dataStyle} onChange={e=>p.applyDataStyle(e.target.value)}><option value="custom">Custom</option>{p.dataStyleOptions.map(([k,v]:any)=><option key={k} value={k}>{v.name}</option>)}</select></label><label>Entity <input type="color" value={p.colors.entity} onChange={e=>p.updateDataColor('entity',e.target.value)}/></label><label>H3 Fill <input type="color" value={p.colors.fill} onChange={e=>p.updateDataColor('fill',e.target.value)}/></label><label>H3 Border <input type="color" value={p.colors.line} onChange={e=>p.updateDataColor('line',e.target.value)}/></label><label>Opacity <input type="range" min="0" max="1" step=".01" value={p.colors.opacity} onChange={e=>p.updateDataColor('opacity',+e.target.value)}/></label><button className="full" onClick={()=>p.applyDataStyle('default')}>Reset Default</button></div>
 <div className="section"><b>Analytics</b><label>Map Metric<select value={p.analyticsMode} onChange={e=>{p.setAnalyticsMode(e.target.value);localStorage.setItem('h3-analytics-mode',e.target.value)}}><option value="off">Off</option><option value="entity_count">Entity Count</option><option value="coverage">Polygon Coverage</option></select></label><small className="sectionHint">{p.analyticsRows.length.toLocaleString()} H3 analytics rows</small></div>
 <div className="section"><b>3D Data Height</b><Check t="Extrude H3" v={p.extruded3d} s={(v:boolean)=>{p.setExtruded3d(v);localStorage.setItem('h3-extruded-3d',String(v))}}/><label>Height <b>{p.height3d.toLocaleString()} m</b><input type="range" min="0" max="2000" step="10" value={p.height3d} onChange={e=>{const v=+e.target.value;p.setHeight3d(v);localStorage.setItem('h3-height-3d',String(v))}}/></label></div>
 <div className="section"><b>H3 Display — Res {p.resolution}</b><input type="range" min="5" max="15" value={p.resolution} onChange={e=>p.setResolution(+e.target.value)}/><div className="resGrid">{Array.from({length:11},(_,i)=>i+5).map(r=><button className={r===p.resolution?'active':''} key={r} onClick={()=>p.setResolution(r)}>{r}</button>)}</div></div>
 <div className="section"><b>Advanced Query</b><select id="qField"><option>attribute</option><option>properties.category</option><option>properties.name</option><option>entity_id</option><option>h3_index</option><option>resolution</option></select><select id="qOp"><option>=</option><option>!=</option><option>contains</option></select><input id="qValue" placeholder="value"/><select id="qSpatial"><option value="none">None</option><option value="nearby">Nearby</option><option value="bbox">BBox</option></select><input id="qDistance" type="number" defaultValue="1000"/><button className="primary full" onClick={p.runQuery}>Run Query</button></div>
 <div className="section"><b>Basemap</b><select value={p.basemap} onChange={e=>p.setBasemap(e.target.value)}>{Object.entries(BASEMAPS).map(([k,v]:any)=><option key={k} value={k}>{v.name}</option>)}</select></div></aside>}
function Check({t,v,s}:{t:string;v:boolean;s:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={v} onChange={e=>s(e.target.checked)}/>{t}</label>}
function Results({data,close}:{data:any[];close:()=>void}){return <aside className="panel results"><div className="panelHead"><b>Results ({data.length})</b><button onClick={close}>×</button></div><div className="resultList">{data.slice(0,500).map((x,i)=><div className="result" key={i}><b>{x.hex||x.entity_id||'Result'}</b><pre>{JSON.stringify(x,null,2)}</pre></div>)}</div></aside>}

function DatasetsPage({datasets,refresh,onViewMap,onNew,onNotify}:{datasets:Dataset[];refresh:()=>void;onViewMap:(name:string)=>void;onNew:()=>void;onNotify:(x:string)=>void}){
 const [detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(false),[editing,setEditing]=useState(false);
 const [name,setName]=useState(''),[metadata,setMetadata]=useState('{}'),[search,setSearch]=useState('');
 const [catalog,setCatalog]=useState<any>({source:'',owner:'',version:'1.0.0',source_format:'',license:'',update_frequency:'',tags:'',geographic_coverage:'{}',schema:'{}',lineage:'{}'});
 const filtered=useMemo(()=>datasets.filter(d=>d.dataset.toLowerCase().includes(search.toLowerCase())||d.data_type.toLowerCase().includes(search.toLowerCase())),[datasets,search]);
 const open=async(id:number)=>{setLoading(true);try{const r=await fetch(API+'/datasets/'+id);const d=await r.json();if(!r.ok)throw Error(d.detail||'Dataset not found');setDetail(d);setName(d.name);setMetadata(JSON.stringify(d.metadata||{},null,2));setCatalog({source:d.source||'',owner:d.owner||'',version:d.version||'1.0.0',source_format:d.source_format||'',license:d.license||'',update_frequency:d.update_frequency||'',tags:(d.tags||[]).join(', '),geographic_coverage:JSON.stringify(d.geographic_coverage||{},null,2),schema:JSON.stringify(d.schema||{},null,2),lineage:JSON.stringify(d.lineage||{},null,2)});setEditing(false)}catch(e){onNotify(e instanceof Error?e.message:'Load failed')}finally{setLoading(false)}};
 const remove=async(id:number,n:string)=>{if(!confirm('Delete dataset '+n+' และข้อมูลทั้งหมด?'))return;try{const r=await fetch(API+'/datasets/'+id,{method:'DELETE'});const d=await r.json();if(!r.ok)throw Error(d.detail||'Delete failed');if(detail?.dataset_id===id)setDetail(null);onNotify('ลบ Dataset '+n+' แล้ว');refresh()}catch(e){onNotify(e instanceof Error?e.message:'Delete failed')}};
 const save=async()=>{if(!detail)return;let meta:any;try{meta=JSON.parse(metadata)}catch{return onNotify('Metadata ต้องเป็น JSON ที่ถูกต้อง')};let geographic_coverage:any={},schema:any={},lineage:any={};try{geographic_coverage=JSON.parse(catalog.geographic_coverage||'{}');schema=JSON.parse(catalog.schema||'{}');lineage=JSON.parse(catalog.lineage||'{}')}catch{return onNotify('Catalog JSON ต้องเป็น JSON ที่ถูกต้อง')};const payload={name:name.trim(),metadata:meta,source:catalog.source,owner:catalog.owner,version:catalog.version,source_format:catalog.source_format,license:catalog.license,update_frequency:catalog.update_frequency,tags:String(catalog.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean),geographic_coverage,schema,lineage};try{const r=await fetch(API+'/datasets/'+detail.dataset_id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.detail||'Update failed');setDetail((x:any)=>({...x,...d}));setName(d.name);setMetadata(JSON.stringify(d.metadata||{},null,2));setCatalog({source:d.source||'',owner:d.owner||'',version:d.version||'1.0.0',source_format:d.source_format||'',license:d.license||'',update_frequency:d.update_frequency||'',tags:(d.tags||[]).join(', '),geographic_coverage:JSON.stringify(d.geographic_coverage||{},null,2),schema:JSON.stringify(d.schema||{},null,2),lineage:JSON.stringify(d.lineage||{},null,2)});setEditing(false);onNotify('บันทึก Dataset แล้ว');refresh()}catch(e){onNotify(e instanceof Error?e.message:'Update failed')}};
 if(detail)return <section className="page"><div className="pageHeader"><div><button onClick={()=>setDetail(null)}>← Datasets</button><h2 style={{marginTop:10}}>{detail.name}</h2><p>Dataset Detail · ID {detail.dataset_id}</p></div><div className="buttonRow"><button onClick={()=>onViewMap(detail.name)}>View on Map</button><button onClick={()=>setEditing(!editing)}>{editing?'Cancel':'Edit'}</button><button className="primary" onClick={()=>open(detail.dataset_id)}>Refresh</button><button onClick={()=>remove(detail.dataset_id,detail.name)}>Delete</button></div></div>
  <div className="kpis"><b>{Number(detail.entity_count||0).toLocaleString()}<small>Entities</small></b><b>{Number(detail.part_count||0).toLocaleString()}<small>Parts</small></b><b>{Number(detail.boundary_h3_count||0).toLocaleString()}<small>Boundary H3</small></b><b>Res {detail.h3_resolution}<small>Dataset Resolution</small></b></div>
  <div className="grid2" style={{marginTop:12}}><div className="card"><b>Dataset Configuration</b>{editing?<><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>H3 Resolution<input value={detail.h3_resolution} disabled/></label><div className="page-note">H3 Resolution ถูกล็อกไว้เพื่อไม่ให้เปลี่ยน configuration โดยไม่ rebuild H3 coverage ใหม่</div></>:<><p>Type: <b>{detail.data_type}</b></p><p>H3 Resolution: <b>Res {detail.h3_resolution}</b></p><p>Storage: <b>{detail.storage_mode||'boundary_h3'}</b></p><p>Created: {String(detail.created_at||'').slice(0,19)}</p><p>Updated: {String(detail.updated_at||'').slice(0,19)}</p></>}</div>
  <div className="card"><b>Metadata</b>{editing?<><textarea className="metadataEditor" value={metadata} onChange={e=>setMetadata(e.target.value)}/><button className="primary" onClick={save}>Save Changes</button></>:<pre className="preview">{JSON.stringify(detail.metadata||{},null,2)}</pre>}</div>
  <div className="card catalogCard"><b>Data Catalog</b>{editing?<div className="grid2"><label>Source<input value={catalog.source} onChange={e=>setCatalog({...catalog,source:e.target.value})}/></label><label>Owner<input value={catalog.owner} onChange={e=>setCatalog({...catalog,owner:e.target.value})}/></label><label>Version<input value={catalog.version} onChange={e=>setCatalog({...catalog,version:e.target.value})}/></label><label>Source Format<input value={catalog.source_format} onChange={e=>setCatalog({...catalog,source_format:e.target.value})}/></label><label>License<input value={catalog.license} onChange={e=>setCatalog({...catalog,license:e.target.value})}/></label><label>Update Frequency<input value={catalog.update_frequency} onChange={e=>setCatalog({...catalog,update_frequency:e.target.value})}/></label><label>Tags<input value={catalog.tags} onChange={e=>setCatalog({...catalog,tags:e.target.value})} placeholder="tag1, tag2"/></label><label>Geographic Coverage<textarea className="metadataEditor" value={catalog.geographic_coverage} onChange={e=>setCatalog({...catalog,geographic_coverage:e.target.value})}/></label><label>Schema<textarea className="metadataEditor" value={catalog.schema} onChange={e=>setCatalog({...catalog,schema:e.target.value})}/></label><label>Lineage<textarea className="metadataEditor" value={catalog.lineage} onChange={e=>setCatalog({...catalog,lineage:e.target.value})}/></label></div>:<div className="catalogGrid"><div>Source<br/><b>{detail.source||'—'}</b></div><div>Owner<br/><b>{detail.owner||'—'}</b></div><div>Version<br/><b>{detail.version||'—'}</b></div><div>Format<br/><b>{detail.source_format||'—'}</b></div><div>License<br/><b>{detail.license||'—'}</b></div><div>Update Frequency<br/><b>{detail.update_frequency||'—'}</b></div><div>Tags<br/><b>{(detail.tags||[]).join(', ')||'—'}</b></div><div>Geographic Coverage<br/><pre className="preview">{JSON.stringify(detail.geographic_coverage||{},null,2)}</pre></div><div>Schema<br/><pre className="preview">{JSON.stringify(detail.schema||{},null,2)}</pre></div><div>Lineage<br/><pre className="preview">{JSON.stringify(detail.lineage||{},null,2)}</pre></div></div>}</div></div>
  </section>;
 return <section className="page"><div className="pageHeader"><div><h2>Datasets</h2><p>Dataset Registry · ดูรายละเอียด แก้ไข metadata เปิดบน Map และลบ Dataset</p></div><div className="buttonRow"><button onClick={refresh}>Refresh</button><button className="primary" onClick={onNew}>New Dataset</button></div></div>
  <div className="card"><div className="buttonRow"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหา Dataset หรือ Data Type..."/><span className="badge">{filtered.length}/{datasets.length}</span></div>
   {filtered.length?<div style={{overflowX:'auto'}}><table><thead><tr><th>Dataset</th><th>Type</th><th>H3</th><th>Entities</th><th>Parts</th><th>Boundary H3</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{filtered.map(d=><tr key={d.dataset_id}><td><b>{d.dataset}</b></td><td>{d.data_type}</td><td>Res {d.h3_resolution}</td><td>{Number(d.feature_count||0).toLocaleString()}</td><td>{Number(d.part_count||0).toLocaleString()}</td><td>{Number(d.boundary_h3_count||0).toLocaleString()}</td><td>{String(d.updated_at||'').slice(0,19)}</td><td><div className="buttonRow"><button onClick={()=>open(d.dataset_id)}>Open</button><button onClick={()=>onViewMap(d.dataset)}>Map</button><button onClick={()=>remove(d.dataset_id,d.dataset)}>Delete</button></div></td></tr>)}</tbody></table></div>:<div className="empty">ยังไม่มี Dataset ที่ตรงกับคำค้น</div>}
  </div>{loading&&<div className="card">Loading Dataset Detail…</div>}</section>
}
